<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Minifier\Module'                              => __DIR__ . '/Module.php',
    'Minifier\Controller\MinifierController'       => __DIR__ . '/src/Minifier/Controller/MinifierController.php',
    'Minifier\Controller\Factory'                  => __DIR__ . '/src/Minifier/Controller/Factory.php',
    'Minifier\Controller\Minifier'                 => __DIR__ . '/src/Minifier/Controller/Minifier.php',
    'Minifier\Controller\Adapter\AdapterInterface' => __DIR__ . '/src/Minifier/Controller/Adapter/AdapterInterface.php',
    'Minifier\Controller\Adapter\Minify'           => __DIR__ . '/src/Minifier/Controller/Adapter/Minify.php',
    'Minifier\Controller\View\Helper\BundlePath'   => __DIR__ . '/src/Minifier/Controller/View/Helper/BundlePath.php',

    'Minifier\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Minifier\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);